### ISSUE TITLE
Undefined MS_library.list_similars_ctr_idx, MS_library.list_similars_ctr and M_sim_mol in iomega-10-spectra-networking.ipynb

### ISSUE THREAD

**Issue by chetankm1992** [iomega/spec2vec_gnps_data_analysis#9]
Hi,

I am trying to run **iomega-10-spectra-networking.ipynb** but I am getting error that these ****MS_library** is not defined** and also corresponding variables seems to be **undefined (MS_library.list_similars_ctr_idx, MS_library.list_similars_ctr) at cell 14.** Also **M_sim_mol is not defined before use cell 16.** Please see the attached image (cell number can be different in the image, they are referenced from the following link: [https://github.com/iomega/spec2vec_gnps_data_analysis/blob/master/notebooks/iomega-10-spectra-networking.ipynb](url)

![image](https://user-images.githubusercontent.com/28491233/129107431-dfab1d53-3200-49b7-911d-21a160b33651.png)

Thanks.

**Comment by justinjjvanderhooft** [comment]
Thanks for alerting us. Did you attempt to run earlier notebooks as well? What is your goal with the analysis? We may be able to help you better if we know.
 
For your information: the networking notebook is quite experimental and we are aware this needs further work. If you are happy to help us out, feel free to make suggestions or update the notebook/workflow!

**Comment by florian-huber** [comment]
Looks like there are some parts missing in the notebook. I will see if I find the time to fix it soon!

**Comment by chetankm1992** [comment]
Thank you so much @justinjjvanderhooft and @florian-huber for your quick response. 
The task I am trying do is that I have MS2 data in mgf file format which I have extracted from mzML files (I am not sure if I directly input mzML files to spec2vec method) and then first I want to do spectral similarity which I am able to do using spec2vec method. After that I want to do MS2 clustering where I can merge most similar spectra and further create a network between them, for that I tried to use the above mentioned jupyter notebook on GNPS data first but it gives error, so I am not sure how can I apply on my data and moreover my data is not annotated, I do not have inchikey or smile as I noticed this notebook requires fingerprint so I am not sure how it can be applied on some data which do not have any type of labels.

The next task I want to do is library matching where I can annotate my data. For that I am trying one of your notebooks (**iomega-8-library-matching-pre_revision**) but I am getting some errors as shown in attached image. Let's say if I pass **found_matches_s2v** or **found_matches_classical** instead of **found_matches** but then I get **mass_match** undefined. 
![image](https://user-images.githubusercontent.com/28491233/129213173-481341f7-ab81-4c5a-ac88-f2943a8ce165.png)

Similarly if I try **iomega-8-library-matching-scenario1** notebook then I get error as shown in following image.
![image](https://user-images.githubusercontent.com/28491233/129213335-e5fb4de5-9fd7-461d-87bd-7a1da9126e40.png)

Could you help me with the tasks I mentioned and if it possible to do with current method where I do not have annotated data but I want to create network based on spectral similarity and do library matching. Thanks

**Comment by florian-huber** [comment]
Thanks for clarifying things @chetankm1992!

That sounds like you are less interested in fully running the mentioned notebooks, but your goal is to run molecular networking/clustering on your data, and do library matching.

I will still aim to update/fix the mentioned notebooks, but it seems it would make more sense if I first concentrate on (finally!) finishing part 3 of our tutorial (https://blog.esciencecenter.nl/build-a-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-ii-spec2vec-8aa639571018).

**Comment by chetankm1992** [comment]
Thanks @florian-huber. I have already went through both of the tutorials (that's how I got to know about these methods matchms and spec2vec) and have implemented them on my data. I am looking forward for the part 3 of the tutorial where you mentioned you will do network analysis based on spectra similarity. Could I ask when you are planning to upload that tutorial, I am working on some task and it would be helpful if you can upload that tutorial or share some suggestions so that I can do molecular clustering and networking. Thanks.

**Comment by florian-huber** [comment]
Writing the blog post might take a bit of time. But I just uploaded a notebook that I plan to use as a basis for the post.
Please have a look and let me know if that helps you further: https://github.com/matchms/matchms/blob/tutorial/tutorial/matchms_tutorial_03_create_graph_from_Spec2Vec_similarities.ipynb

**Comment by chetankm1992** [comment]
Thank you so much @florian-huber for uploading this notebook and it is very helpful. I will try to run it on my data and do analysis and will also try to use Cytoscape on this network. Just one more question is that lets say you find out the similarity between different spectra and find a cluster then how can you merge these similar spectra into one node or in other words how can you convert each cluster into one node to reduce the redundancy when lets say creating the network or doing spectra matching with online libraries (also is there a way to do library matching online). It would make sense when we have multiple mzML files and some of the files will have same data (spectra), so we can use similarity matching technique to merge the similar spectra and remove the redundancy. Thanks

**Comment by justinjjvanderhooft** [comment]
That is good point indeed. The MSClust algorithm was developed to do this (based on very high cosine score similarity - then this score works perfectly fine) - you could either implement it yourself or run classical molecular networking at GNPS (I believe you are familiar with the web service), and download the resulting MGF file that contains the aggregated (consensus) spectra of all the files - in the metadata you can find in which files each spectrum is present. Have fun!

**Comment by chetankm1992** [comment]
Thanks @justinjjvanderhooft , I have used GNPS web app but never downloaded a resulting MGF, I will take a try. Thanks both @justinjjvanderhooft and @florian-huber for your quick and very helpful response :)

**Comment by florian-huber** [comment]
Perfect, thanks @chetankm1992.

And I now also posted a first blog post on this: https://blog.esciencecenter.nl/build-a-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-iii-molecular-91891248ee34

@justinjjvanderhooft and @chetankm1992 let me know if you have any further edits/comments/suggestions for this. Thanks!

**Comment by justinjjvanderhooft** [comment]
Looks good to me @florian-huber! You could consider adding the network figure from our poster at the Metabolomics2019 meeting as it shows some structures and compound classes to further illustrate the usefulness.
